working_directory: .cache

run:
  # - data.sirene.download.siret
  # - data.sirene.download.siren
  # - data.sirene.download.geoloc
  # - data.sirene.raw.siren
  # - data.sirene.localized
  # - data.sirene.cleaned.horizon
  - data.sirene.cleaned.compare
  - data.sirene.output


config:
  processes : 8

  regions: []
  departments: [44]
  municipalities: [44109]

  sirene_cleaning_method: "horizon"
  sirene_output_csv_path: "D:/SOLID/solid-pipeline/sirane_cleaned_horizon.csv"