working_directory: .cache

run:
  # - data.sirene.download.siret
  # - data.sirene.download.siren
  # - data.sirene.download.geoloc
  # - data.sirene.raw.siren
  # - data.sirene.localized
  # - data.sirene.cleaned.horizon
  - data.sirene.cleaned.compare


config:
  processes : 8

  regions: []
  departments: [44]
  municipalities: [44109]

  sirene_cleaning_method: "horizon"