working_directory: .cache

run:
  # - data.sirene.download.siret
  # - data.sirene.download.siren
  # - data.sirene.download.geoloc
  # - data.sirene.raw.siren
  # - data.sirene.localized
  # - data.sirene.cleaned.horizon
  # - data.sirene.cleaned.compare
  # - data.hubs.output
  # - data.sirene.output
  # - movements.output
  # - data.ugms.raw
  # - data.ugms.goods_distributions
  # - data.ugms.vehicles_distributions
  - vehicles.all

config:
  processes : 8

  regions: []
  departments: [75]
  municipalities: []

  sirene_cleaning_method: "horizon"

  sirene_compare_method_output: "D:/SOLID/solid-pipeline/.output/"
  sirene_output_path: "D:/SOLID/solid-pipeline/.output/sirene.geojson"
  hubs_output_path: "D:/SOLID/solid-pipeline/.output/hubs.geojson"
  movements_output_path: "D:/SOLID/solid-pipeline/.output/movements.geojson"
  
  ugms_file_path: "D:/SOLID/data-national/UGMS/Envoi_RIF_dec_2015_base_15_06_04.xlsx"
